# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os
import unittest
from tests.http_response_catcher import HttpResponseCatcher
from aviationstack.configuration import Configuration, Environment
from aviationstack.aviationstack_client import AviationstackClient
from aviationstack.http.auth.custom_query_authentication import CustomQueryAuthenticationCredentials


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = AviationstackClient(config=cls.config)

    @staticmethod
    def create_configuration():
        environment = os.getenv('AVIATIONSTACK_ENVIRONMENT')
        access_key = os.getenv('AVIATIONSTACK_ACCESS_KEY')

        if environment is not None:
            environment = Environment[environment.upper()]
        custom_query_authentication_credentials=None
        if access_key is not None:
            custom_query_authentication_credentials=CustomQueryAuthenticationCredentials(
                access_key=access_key)


        config = Configuration(http_call_back=HttpResponseCatcher())
        return config.clone_with(
            custom_query_authentication_credentials=custom_query_authentication_credentials,
            environment=environment)

