# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from aviationstack.api_helper import APIHelper


class AircraftTypesControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(AircraftTypesControllerTests, cls).setUpClass()
        cls.controller = cls.client.aircraft_types
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_aircraft_types
    def test_aircraft_types(self):

        # Perform the API call through the SDK function
        result = self.controller.aircraft_types()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['cache-control'] = None
        expected_headers['x-request-time'] = None
        expected_headers['x-apilayer-transaction-id'] = None
        expected_headers['access-control-allow-origin'] = None
        expected_headers['access-control-allow-methods'] = None
        expected_headers['access-control-allow-headers'] = None
        expected_headers['x-quota-limit'] = None
        expected_headers['x-quota-remaining'] = None
        expected_headers['x-increment-usage'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['report-to'] = None
        expected_headers['nel'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-encoding'] = None
        expected_headers['alt-svc'] = None

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"pagination":{"offset":0,"limit":100,"count":100,"total":313},"da'
            'ta":[{"id":"16907","iata_code":"100","aircraft_name":"Fokker 100",'
            '"plane_type_id":"1"},{"id":"16908","iata_code":"141","aircraft_nam'
            'e":"British Aerospace BAe 146-100","plane_type_id":"2"},{"id":"169'
            '09","iata_code":"142","aircraft_name":"British Aerospace BAe 146-2'
            '00","plane_type_id":"3"},{"id":"16910","iata_code":"143","aircraft'
            '_name":"British Aerospace BAe 146-300","plane_type_id":"4"},{"id":'
            '"16911","iata_code":"146","aircraft_name":"British Aerospace BAe 1'
            '46","plane_type_id":"5"},{"id":"16912","iata_code":"14F","aircraft'
            '_name":"British Aerospace BAe 146 Freighter","plane_type_id":"6"},'
            '{"id":"16913","iata_code":"14X","aircraft_name":"British Aerospace'
            ' BAe 146-100QT/QC","plane_type_id":"7"},{"id":"16914","iata_code":'
            '"14Y","aircraft_name":"British Aerospace BAe 146-200QT/QC","plane_'
            'type_id":"8"},{"id":"16915","iata_code":"14Z","aircraft_name":"Bri'
            'tish Aerospace BAe 146-300QT/QC","plane_type_id":"9"},{"id":"16916'
            '","iata_code":"310","aircraft_name":"Airbus Industrie A310","plane'
            '_type_id":"10"},{"id":"16917","iata_code":"312","aircraft_name":"A'
            'irbus Industrie A310-200","plane_type_id":"11"},{"id":"16918","iat'
            'a_code":"313","aircraft_name":"Airbus Industrie A310-300","plane_t'
            'ype_id":"12"},{"id":"16919","iata_code":"318","aircraft_name":"Air'
            'bus Industrie A318","plane_type_id":"13"},{"id":"16920","iata_code'
            '":"319","aircraft_name":"Airbus Industrie A319","plane_type_id":"1'
            '4"},{"id":"16921","iata_code":"31F","aircraft_name":"Airbus Indust'
            'rie A310 Freighter","plane_type_id":"15"},{"id":"16922","iata_code'
            '":"31X","aircraft_name":"Airbus Industrie A310-200 Freighter","pla'
            'ne_type_id":"16"},{"id":"16923","iata_code":"31Y","aircraft_name":'
            '"Airbus Industrie A310-300 Freighter","plane_type_id":"17"},{"id":'
            '"16924","iata_code":"320","aircraft_name":"Airbus Industrie A320",'
            '"plane_type_id":"18"},{"id":"16925","iata_code":"321","aircraft_na'
            'me":"Airbus Industrie A321","plane_type_id":"19"},{"id":"16926","i'
            'ata_code":"32S","aircraft_name":"Airbus Industrie A318/319/320/321'
            '","plane_type_id":"20"},{"id":"16927","iata_code":"330","aircraft_'
            'name":"Airbus Industrie A330","plane_type_id":"21"},{"id":"16928",'
            '"iata_code":"332","aircraft_name":"Airbus Industrie A330-200","pla'
            'ne_type_id":"22"},{"id":"16929","iata_code":"333","aircraft_name":'
            '"Airbus Industrie A330-300","plane_type_id":"23"},{"id":"16930","i'
            'ata_code":"340","aircraft_name":"Airbus Industrie A340","plane_typ'
            'e_id":"24"},{"id":"16931","iata_code":"342","aircraft_name":"Airbu'
            's Industrie A340-200","plane_type_id":"25"},{"id":"16932","iata_co'
            'de":"343","aircraft_name":"Airbus Industrie A340-300","plane_type_'
            'id":"26"},{"id":"16933","iata_code":"345","aircraft_name":"Airbus '
            'Industrie A340-500","plane_type_id":"27"},{"id":"16934","iata_code'
            '":"346","aircraft_name":"Airbus Industrie A340-600","plane_type_id'
            '":"28"},{"id":"16935","iata_code":"380","aircraft_name":"Airbus In'
            'dustrie A380","plane_type_id":"29"},{"id":"16936","iata_code":"388'
            '","aircraft_name":"Airbus Industrie A380-800","plane_type_id":"30"'
            '},{"id":"16937","iata_code":"38F","aircraft_name":"Airbus Industri'
            'e A380 Freighter","plane_type_id":"31"},{"id":"16938","iata_code":'
            '"703","aircraft_name":"Boeing 707-300","plane_type_id":"32"},{"id"'
            ':"16939","iata_code":"707","aircraft_name":"Boeing 707/720","plane'
            '_type_id":"33"},{"id":"16940","iata_code":"70F","aircraft_name":"B'
            'oeing 707-300 Freighter","plane_type_id":"34"},{"id":"16941","iata'
            '_code":"70M","aircraft_name":"Boeing 707-300 Combi","plane_type_id'
            '":"35"},{"id":"16942","iata_code":"717","aircraft_name":"Boeing 71'
            '7-200","plane_type_id":"36"},{"id":"16943","iata_code":"721","airc'
            'raft_name":"Boeing 727-100","plane_type_id":"37"},{"id":"16944","i'
            'ata_code":"722","aircraft_name":"Boeing 727-200","plane_type_id":"'
            '38"},{"id":"16945","iata_code":"727","aircraft_name":"Boeing 727",'
            '"plane_type_id":"39"},{"id":"16946","iata_code":"72A","aircraft_na'
            'me":"Boeing 727-200 Advanced","plane_type_id":"40"},{"id":"16947",'
            '"iata_code":"72B","aircraft_name":"Boeing 727-100 Combi","plane_ty'
            'pe_id":"41"},{"id":"16948","iata_code":"72C","aircraft_name":"Boei'
            'ng 727-200 Combi","plane_type_id":"42"},{"id":"16949","iata_code":'
            '"72F","aircraft_name":"Boeing 727 Freighter","plane_type_id":"43"}'
            ',{"id":"16950","iata_code":"72M","aircraft_name":"Boeing 727 Combi'
            '","plane_type_id":"44"},{"id":"16951","iata_code":"72S","aircraft_'
            'name":"Boeing 727-200","plane_type_id":"45"},{"id":"16952","iata_c'
            'ode":"72X","aircraft_name":"Boeing 727-100 Freighter","plane_type_'
            'id":"46"},{"id":"16953","iata_code":"72Y","aircraft_name":"Boeing '
            '727-200 Freighter","plane_type_id":"47"},{"id":"16954","iata_code"'
            ':"731","aircraft_name":"Boeing 737-100","plane_type_id":"48"},{"id'
            '":"16955","iata_code":"732","aircraft_name":"Boeing 737-200","plan'
            'e_type_id":"49"},{"id":"16956","iata_code":"733","aircraft_name":"'
            'Boeing 737-300","plane_type_id":"50"},{"id":"16957","iata_code":"7'
            '34","aircraft_name":"Boeing 737-400","plane_type_id":"51"},{"id":"'
            '16958","iata_code":"735","aircraft_name":"Boeing 737-500","plane_t'
            'ype_id":"52"},{"id":"16959","iata_code":"736","aircraft_name":"Boe'
            'ing 737-600","plane_type_id":"53"},{"id":"16960","iata_code":"737"'
            ',"aircraft_name":"Boeing 737","plane_type_id":"54"},{"id":"16961",'
            '"iata_code":"738","aircraft_name":"Boeing 737-800","plane_type_id"'
            ':"55"},{"id":"16962","iata_code":"739","aircraft_name":"Boeing 737'
            '-900","plane_type_id":"56"},{"id":"16963","iata_code":"73A","aircr'
            'aft_name":"Boeing 737-200/200C Advanced","plane_type_id":"57"},{"i'
            'd":"16964","iata_code":"73C","aircraft_name":"Boeing 737-300","pla'
            'ne_type_id":"58"},{"id":"16965","iata_code":"73E","aircraft_name":'
            '"Boeing 737-900ER","plane_type_id":"59"},{"id":"16966","iata_code"'
            ':"73F","aircraft_name":"Boeing 737 Freighter","plane_type_id":"60"'
            '},{"id":"16967","iata_code":"73G","aircraft_name":"Boeing 737-700"'
            ',"plane_type_id":"61"},{"id":"16968","iata_code":"73H","aircraft_n'
            'ame":"Boeing 737-800 With Winglets","plane_type_id":"62"},{"id":"1'
            '6969","iata_code":"73J","aircraft_name":"Boeing 737-900 With Wingl'
            'ets","plane_type_id":"63"},{"id":"16970","iata_code":"73M","aircra'
            'ft_name":"Boeing 737-200 Combi","plane_type_id":"64"},{"id":"16971'
            '","iata_code":"73N","aircraft_name":"Boeing 737-300 Mixed Config",'
            '"plane_type_id":"65"},{"id":"16972","iata_code":"73P","aircraft_na'
            'me":"Boeing 737-400 Freighter","plane_type_id":"66"},{"id":"16973"'
            ',"iata_code":"73Q","aircraft_name":"Boeing 737-400 Mixed Config","'
            'plane_type_id":"67"},{"id":"16974","iata_code":"73S","aircraft_nam'
            'e":"Boeing 737 Advanced","plane_type_id":"68"},{"id":"16975","iata'
            '_code":"73W","aircraft_name":"Boeing 737-700 With Winglets","plane'
            '_type_id":"69"},{"id":"16976","iata_code":"73X","aircraft_name":"B'
            'oeing 737-200 Freighter","plane_type_id":"70"},{"id":"16977","iata'
            '_code":"73Y","aircraft_name":"Boeing 737-300 Freighter","plane_typ'
            'e_id":"71"},{"id":"16978","iata_code":"741","aircraft_name":"Boein'
            'g 747-100","plane_type_id":"72"},{"id":"16979","iata_code":"742","'
            'aircraft_name":"Boeing 747-200","plane_type_id":"73"},{"id":"16980'
            '","iata_code":"743","aircraft_name":"Boeing 747-300 (including -10'
            '0SUD and -200SUD)","plane_type_id":"74"},{"id":"16981","iata_code"'
            ':"744","aircraft_name":"Boeing 747-400","plane_type_id":"75"},{"id'
            '":"16982","iata_code":"747","aircraft_name":"Boeing 747","plane_ty'
            'pe_id":"76"},{"id":"16983","iata_code":"74C","aircraft_name":"Boei'
            'ng 747-200 Combi","plane_type_id":"77"},{"id":"16984","iata_code":'
            '"74D","aircraft_name":"Boeing 747-300 Combi (including -200SUD)","'
            'plane_type_id":"78"},{"id":"16985","iata_code":"74E","aircraft_nam'
            'e":"Boeing 747-400 Combi","plane_type_id":"79"},{"id":"16986","iat'
            'a_code":"74F","aircraft_name":"Boeing 747 Freighter","plane_type_i'
            'd":"80"},{"id":"16987","iata_code":"74J","aircraft_name":"Boeing 7'
            '47-400 Domestic","plane_type_id":"81"},{"id":"16988","iata_code":"'
            '74L","aircraft_name":"Boeing 747SP","plane_type_id":"82"},{"id":"1'
            '6989","iata_code":"74M","aircraft_name":"Boeing 747 Combi","plane_'
            'type_id":"83"},{"id":"16990","iata_code":"74T","aircraft_name":"Bo'
            'eing 747-100 Freighter","plane_type_id":"84"},{"id":"16991","iata_'
            'code":"74U","aircraft_name":"Boeing 747-300 Freighter","plane_type'
            '_id":"85"},{"id":"16992","iata_code":"74V","aircraft_name":"Boeing'
            ' 747SR Freighter","plane_type_id":"86"},{"id":"16993","iata_code":'
            '"74X","aircraft_name":"Boeing 747-200 Freighter","plane_type_id":"'
            '87"},{"id":"16994","iata_code":"74Y","aircraft_name":"Boeing 747-4'
            '00 Freighter","plane_type_id":"88"},{"id":"16995","iata_code":"752'
            '","aircraft_name":"Boeing 757-200","plane_type_id":"89"},{"id":"16'
            '996","iata_code":"753","aircraft_name":"Boeing 757-300","plane_typ'
            'e_id":"90"},{"id":"16997","iata_code":"757","aircraft_name":"Boein'
            'g 757","plane_type_id":"91"},{"id":"16998","iata_code":"75F","airc'
            'raft_name":"Boeing 757-200 Freighter","plane_type_id":"92"},{"id":'
            '"16999","iata_code":"75M","aircraft_name":"Boeing 757-200 Combi","'
            'plane_type_id":"93"},{"id":"17000","iata_code":"75W","aircraft_nam'
            'e":"Boeing 757-200 With Winglets","plane_type_id":"94"},{"id":"170'
            '01","iata_code":"762","aircraft_name":"Boeing 767-200","plane_type'
            '_id":"95"},{"id":"17002","iata_code":"763","aircraft_name":"Boeing'
            ' 767-300","plane_type_id":"96"},{"id":"17003","iata_code":"764","a'
            'ircraft_name":"Boeing 767-400","plane_type_id":"97"},{"id":"17004"'
            ',"iata_code":"767","aircraft_name":"Boeing 767","plane_type_id":"9'
            '8"},{"id":"17005","iata_code":"76F","aircraft_name":"Boeing 767 Fr'
            'eighter","plane_type_id":"99"},{"id":"17006","iata_code":"76X","ai'
            'rcraft_name":"Boeing 767-200 Freighter","plane_type_id":"100"}]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Todo: Add description for test test_aircraft_types_1
    def test_aircraft_types_1(self):

        # Perform the API call through the SDK function
        result = self.controller.aircraft_types()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"pagination":{"offset":0,"limit":100,"count":100,"total":313},"da'
            'ta":[{"id":"16907","iata_code":"100","aircraft_name":"Fokker 100",'
            '"plane_type_id":"1"},{"id":"16908","iata_code":"141","aircraft_nam'
            'e":"British Aerospace BAe 146-100","plane_type_id":"2"},{"id":"169'
            '09","iata_code":"142","aircraft_name":"British Aerospace BAe 146-2'
            '00","plane_type_id":"3"},{"id":"16910","iata_code":"143","aircraft'
            '_name":"British Aerospace BAe 146-300","plane_type_id":"4"},{"id":'
            '"16911","iata_code":"146","aircraft_name":"British Aerospace BAe 1'
            '46","plane_type_id":"5"},{"id":"16912","iata_code":"14F","aircraft'
            '_name":"British Aerospace BAe 146 Freighter","plane_type_id":"6"},'
            '{"id":"16913","iata_code":"14X","aircraft_name":"British Aerospace'
            ' BAe 146-100QT/QC","plane_type_id":"7"},{"id":"16914","iata_code":'
            '"14Y","aircraft_name":"British Aerospace BAe 146-200QT/QC","plane_'
            'type_id":"8"},{"id":"16915","iata_code":"14Z","aircraft_name":"Bri'
            'tish Aerospace BAe 146-300QT/QC","plane_type_id":"9"},{"id":"16916'
            '","iata_code":"310","aircraft_name":"Airbus Industrie A310","plane'
            '_type_id":"10"},{"id":"16917","iata_code":"312","aircraft_name":"A'
            'irbus Industrie A310-200","plane_type_id":"11"},{"id":"16918","iat'
            'a_code":"313","aircraft_name":"Airbus Industrie A310-300","plane_t'
            'ype_id":"12"},{"id":"16919","iata_code":"318","aircraft_name":"Air'
            'bus Industrie A318","plane_type_id":"13"},{"id":"16920","iata_code'
            '":"319","aircraft_name":"Airbus Industrie A319","plane_type_id":"1'
            '4"},{"id":"16921","iata_code":"31F","aircraft_name":"Airbus Indust'
            'rie A310 Freighter","plane_type_id":"15"},{"id":"16922","iata_code'
            '":"31X","aircraft_name":"Airbus Industrie A310-200 Freighter","pla'
            'ne_type_id":"16"},{"id":"16923","iata_code":"31Y","aircraft_name":'
            '"Airbus Industrie A310-300 Freighter","plane_type_id":"17"},{"id":'
            '"16924","iata_code":"320","aircraft_name":"Airbus Industrie A320",'
            '"plane_type_id":"18"},{"id":"16925","iata_code":"321","aircraft_na'
            'me":"Airbus Industrie A321","plane_type_id":"19"},{"id":"16926","i'
            'ata_code":"32S","aircraft_name":"Airbus Industrie A318/319/320/321'
            '","plane_type_id":"20"},{"id":"16927","iata_code":"330","aircraft_'
            'name":"Airbus Industrie A330","plane_type_id":"21"},{"id":"16928",'
            '"iata_code":"332","aircraft_name":"Airbus Industrie A330-200","pla'
            'ne_type_id":"22"},{"id":"16929","iata_code":"333","aircraft_name":'
            '"Airbus Industrie A330-300","plane_type_id":"23"},{"id":"16930","i'
            'ata_code":"340","aircraft_name":"Airbus Industrie A340","plane_typ'
            'e_id":"24"},{"id":"16931","iata_code":"342","aircraft_name":"Airbu'
            's Industrie A340-200","plane_type_id":"25"},{"id":"16932","iata_co'
            'de":"343","aircraft_name":"Airbus Industrie A340-300","plane_type_'
            'id":"26"},{"id":"16933","iata_code":"345","aircraft_name":"Airbus '
            'Industrie A340-500","plane_type_id":"27"},{"id":"16934","iata_code'
            '":"346","aircraft_name":"Airbus Industrie A340-600","plane_type_id'
            '":"28"},{"id":"16935","iata_code":"380","aircraft_name":"Airbus In'
            'dustrie A380","plane_type_id":"29"},{"id":"16936","iata_code":"388'
            '","aircraft_name":"Airbus Industrie A380-800","plane_type_id":"30"'
            '},{"id":"16937","iata_code":"38F","aircraft_name":"Airbus Industri'
            'e A380 Freighter","plane_type_id":"31"},{"id":"16938","iata_code":'
            '"703","aircraft_name":"Boeing 707-300","plane_type_id":"32"},{"id"'
            ':"16939","iata_code":"707","aircraft_name":"Boeing 707/720","plane'
            '_type_id":"33"},{"id":"16940","iata_code":"70F","aircraft_name":"B'
            'oeing 707-300 Freighter","plane_type_id":"34"},{"id":"16941","iata'
            '_code":"70M","aircraft_name":"Boeing 707-300 Combi","plane_type_id'
            '":"35"},{"id":"16942","iata_code":"717","aircraft_name":"Boeing 71'
            '7-200","plane_type_id":"36"},{"id":"16943","iata_code":"721","airc'
            'raft_name":"Boeing 727-100","plane_type_id":"37"},{"id":"16944","i'
            'ata_code":"722","aircraft_name":"Boeing 727-200","plane_type_id":"'
            '38"},{"id":"16945","iata_code":"727","aircraft_name":"Boeing 727",'
            '"plane_type_id":"39"},{"id":"16946","iata_code":"72A","aircraft_na'
            'me":"Boeing 727-200 Advanced","plane_type_id":"40"},{"id":"16947",'
            '"iata_code":"72B","aircraft_name":"Boeing 727-100 Combi","plane_ty'
            'pe_id":"41"},{"id":"16948","iata_code":"72C","aircraft_name":"Boei'
            'ng 727-200 Combi","plane_type_id":"42"},{"id":"16949","iata_code":'
            '"72F","aircraft_name":"Boeing 727 Freighter","plane_type_id":"43"}'
            ',{"id":"16950","iata_code":"72M","aircraft_name":"Boeing 727 Combi'
            '","plane_type_id":"44"},{"id":"16951","iata_code":"72S","aircraft_'
            'name":"Boeing 727-200","plane_type_id":"45"},{"id":"16952","iata_c'
            'ode":"72X","aircraft_name":"Boeing 727-100 Freighter","plane_type_'
            'id":"46"},{"id":"16953","iata_code":"72Y","aircraft_name":"Boeing '
            '727-200 Freighter","plane_type_id":"47"},{"id":"16954","iata_code"'
            ':"731","aircraft_name":"Boeing 737-100","plane_type_id":"48"},{"id'
            '":"16955","iata_code":"732","aircraft_name":"Boeing 737-200","plan'
            'e_type_id":"49"},{"id":"16956","iata_code":"733","aircraft_name":"'
            'Boeing 737-300","plane_type_id":"50"},{"id":"16957","iata_code":"7'
            '34","aircraft_name":"Boeing 737-400","plane_type_id":"51"},{"id":"'
            '16958","iata_code":"735","aircraft_name":"Boeing 737-500","plane_t'
            'ype_id":"52"},{"id":"16959","iata_code":"736","aircraft_name":"Boe'
            'ing 737-600","plane_type_id":"53"},{"id":"16960","iata_code":"737"'
            ',"aircraft_name":"Boeing 737","plane_type_id":"54"},{"id":"16961",'
            '"iata_code":"738","aircraft_name":"Boeing 737-800","plane_type_id"'
            ':"55"},{"id":"16962","iata_code":"739","aircraft_name":"Boeing 737'
            '-900","plane_type_id":"56"},{"id":"16963","iata_code":"73A","aircr'
            'aft_name":"Boeing 737-200/200C Advanced","plane_type_id":"57"},{"i'
            'd":"16964","iata_code":"73C","aircraft_name":"Boeing 737-300","pla'
            'ne_type_id":"58"},{"id":"16965","iata_code":"73E","aircraft_name":'
            '"Boeing 737-900ER","plane_type_id":"59"},{"id":"16966","iata_code"'
            ':"73F","aircraft_name":"Boeing 737 Freighter","plane_type_id":"60"'
            '},{"id":"16967","iata_code":"73G","aircraft_name":"Boeing 737-700"'
            ',"plane_type_id":"61"},{"id":"16968","iata_code":"73H","aircraft_n'
            'ame":"Boeing 737-800 With Winglets","plane_type_id":"62"},{"id":"1'
            '6969","iata_code":"73J","aircraft_name":"Boeing 737-900 With Wingl'
            'ets","plane_type_id":"63"},{"id":"16970","iata_code":"73M","aircra'
            'ft_name":"Boeing 737-200 Combi","plane_type_id":"64"},{"id":"16971'
            '","iata_code":"73N","aircraft_name":"Boeing 737-300 Mixed Config",'
            '"plane_type_id":"65"},{"id":"16972","iata_code":"73P","aircraft_na'
            'me":"Boeing 737-400 Freighter","plane_type_id":"66"},{"id":"16973"'
            ',"iata_code":"73Q","aircraft_name":"Boeing 737-400 Mixed Config","'
            'plane_type_id":"67"},{"id":"16974","iata_code":"73S","aircraft_nam'
            'e":"Boeing 737 Advanced","plane_type_id":"68"},{"id":"16975","iata'
            '_code":"73W","aircraft_name":"Boeing 737-700 With Winglets","plane'
            '_type_id":"69"},{"id":"16976","iata_code":"73X","aircraft_name":"B'
            'oeing 737-200 Freighter","plane_type_id":"70"},{"id":"16977","iata'
            '_code":"73Y","aircraft_name":"Boeing 737-300 Freighter","plane_typ'
            'e_id":"71"},{"id":"16978","iata_code":"741","aircraft_name":"Boein'
            'g 747-100","plane_type_id":"72"},{"id":"16979","iata_code":"742","'
            'aircraft_name":"Boeing 747-200","plane_type_id":"73"},{"id":"16980'
            '","iata_code":"743","aircraft_name":"Boeing 747-300 (including -10'
            '0SUD and -200SUD)","plane_type_id":"74"},{"id":"16981","iata_code"'
            ':"744","aircraft_name":"Boeing 747-400","plane_type_id":"75"},{"id'
            '":"16982","iata_code":"747","aircraft_name":"Boeing 747","plane_ty'
            'pe_id":"76"},{"id":"16983","iata_code":"74C","aircraft_name":"Boei'
            'ng 747-200 Combi","plane_type_id":"77"},{"id":"16984","iata_code":'
            '"74D","aircraft_name":"Boeing 747-300 Combi (including -200SUD)","'
            'plane_type_id":"78"},{"id":"16985","iata_code":"74E","aircraft_nam'
            'e":"Boeing 747-400 Combi","plane_type_id":"79"},{"id":"16986","iat'
            'a_code":"74F","aircraft_name":"Boeing 747 Freighter","plane_type_i'
            'd":"80"},{"id":"16987","iata_code":"74J","aircraft_name":"Boeing 7'
            '47-400 Domestic","plane_type_id":"81"},{"id":"16988","iata_code":"'
            '74L","aircraft_name":"Boeing 747SP","plane_type_id":"82"},{"id":"1'
            '6989","iata_code":"74M","aircraft_name":"Boeing 747 Combi","plane_'
            'type_id":"83"},{"id":"16990","iata_code":"74T","aircraft_name":"Bo'
            'eing 747-100 Freighter","plane_type_id":"84"},{"id":"16991","iata_'
            'code":"74U","aircraft_name":"Boeing 747-300 Freighter","plane_type'
            '_id":"85"},{"id":"16992","iata_code":"74V","aircraft_name":"Boeing'
            ' 747SR Freighter","plane_type_id":"86"},{"id":"16993","iata_code":'
            '"74X","aircraft_name":"Boeing 747-200 Freighter","plane_type_id":"'
            '87"},{"id":"16994","iata_code":"74Y","aircraft_name":"Boeing 747-4'
            '00 Freighter","plane_type_id":"88"},{"id":"16995","iata_code":"752'
            '","aircraft_name":"Boeing 757-200","plane_type_id":"89"},{"id":"16'
            '996","iata_code":"753","aircraft_name":"Boeing 757-300","plane_typ'
            'e_id":"90"},{"id":"16997","iata_code":"757","aircraft_name":"Boein'
            'g 757","plane_type_id":"91"},{"id":"16998","iata_code":"75F","airc'
            'raft_name":"Boeing 757-200 Freighter","plane_type_id":"92"},{"id":'
            '"16999","iata_code":"75M","aircraft_name":"Boeing 757-200 Combi","'
            'plane_type_id":"93"},{"id":"17000","iata_code":"75W","aircraft_nam'
            'e":"Boeing 757-200 With Winglets","plane_type_id":"94"},{"id":"170'
            '01","iata_code":"762","aircraft_name":"Boeing 767-200","plane_type'
            '_id":"95"},{"id":"17002","iata_code":"763","aircraft_name":"Boeing'
            ' 767-300","plane_type_id":"96"},{"id":"17003","iata_code":"764","a'
            'ircraft_name":"Boeing 767-400","plane_type_id":"97"},{"id":"17004"'
            ',"iata_code":"767","aircraft_name":"Boeing 767","plane_type_id":"9'
            '8"},{"id":"17005","iata_code":"76F","aircraft_name":"Boeing 767 Fr'
            'eighter","plane_type_id":"99"},{"id":"17006","iata_code":"76X","ai'
            'rcraft_name":"Boeing 767-200 Freighter","plane_type_id":"100"}]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

