# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from aviationstack.api_helper import APIHelper


class AirlinesControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(AirlinesControllerTests, cls).setUpClass()
        cls.controller = cls.client.airlines
        cls.response_catcher = cls.controller.http_call_back

    # Retrieve airline data
    def test_get_airlines(self):
        # Parameters for the API call
        limit = 100
        offset = 0
        iata_code = None
        icao_code = None
        country_code = None

        # Perform the API call through the SDK function
        result = self.controller.get_airlines(limit, offset, iata_code, icao_code, country_code)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


