# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from aviationstack.api_helper import APIHelper


class RoutesControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(RoutesControllerTests, cls).setUpClass()
        cls.controller = cls.client.routes
        cls.response_catcher = cls.controller.http_call_back

    # Retrieve airline route information
    def test_get_routes(self):
        # Parameters for the API call
        limit = 100
        offset = 0
        airline_iata = None
        airline_icao = None

        # Perform the API call through the SDK function
        result = self.controller.get_routes(limit, offset, airline_iata, airline_icao)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


