# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from aviationstack.api_helper import APIHelper


class AirplanesControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(AirplanesControllerTests, cls).setUpClass()
        cls.controller = cls.client.airplanes
        cls.response_catcher = cls.controller.http_call_back

    # Retrieve airplane data
    def test_get_airplanes(self):
        # Parameters for the API call
        limit = 100
        offset = 0
        iata_type_code = None
        registration_number = None

        # Perform the API call through the SDK function
        result = self.controller.get_airplanes(limit, offset, iata_type_code, registration_number)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


