# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from aviationstack.api_helper import APIHelper


class FlightsControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(FlightsControllerTests, cls).setUpClass()
        cls.controller = cls.client.flights
        cls.response_catcher = cls.controller.http_call_back

    # Retrieve real-time and historical flight data
    def test_get_flights(self):
        # Parameters for the API call
        limit = 100
        offset = 0
        flight_iata = None
        flight_icao = None
        airline_iata = None
        airline_icao = None
        flight_number = None
        dep_iata = None
        dep_icao = None
        arr_iata = None
        arr_icao = None
        flight_status = None
        date = None

        # Perform the API call through the SDK function
        result = self.controller.get_flights(limit, offset, flight_iata, flight_icao, airline_iata, airline_icao, flight_number, dep_iata, dep_icao, arr_iata, arr_icao, flight_status, date)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


