# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from aviationstack.api_helper import APIHelper


class TaxesControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(TaxesControllerTests, cls).setUpClass()
        cls.controller = cls.client.taxes
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_taxes
    def test_taxes(self):

        # Perform the API call through the SDK function
        result = self.controller.taxes()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['cache-control'] = None
        expected_headers['x-request-time'] = None
        expected_headers['x-apilayer-transaction-id'] = None
        expected_headers['access-control-allow-origin'] = None
        expected_headers['access-control-allow-methods'] = None
        expected_headers['access-control-allow-headers'] = None
        expected_headers['x-quota-limit'] = None
        expected_headers['x-quota-remaining'] = None
        expected_headers['x-increment-usage'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['report-to'] = None
        expected_headers['nel'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-encoding'] = None
        expected_headers['alt-svc'] = None

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"pagination":{"offset":0,"limit":100,"count":100,"total":521},"da'
            'ta":[{"id":"28135","tax_id":"1","tax_name":"Government Tax","iata_'
            'code":"AB"},{"id":"28136","tax_id":"2","tax_name":"Value Added Tax'
            '","iata_code":"AC"},{"id":"28137","tax_id":"3","tax_name":"Passeng'
            'er Service Charge (International)","iata_code":"AE"},{"id":"28138"'
            ',"tax_id":"4","tax_name":"Airport Departure Fee (Domestic/Internat'
            'ional)","iata_code":"AF"},{"id":"28139","tax_id":"5","tax_name":"T'
            'icket Tax","iata_code":"AG"},{"id":"28140","tax_id":"6","tax_name"'
            ':"Airport Tax","iata_code":"AH"},{"id":"28141","tax_id":"7","tax_n'
            'ame":"Baggage Security Screening Fee","iata_code":"AI"},{"id":"281'
            '42","tax_id":"8","tax_name":"Airport Exit Tax (International)","ia'
            'ta_code":"AJ"},{"id":"28143","tax_id":"9","tax_name":"Airport Depa'
            'rture Tax (International)","iata_code":"AK"},{"id":"28144","tax_id'
            '":"10","tax_name":"Passenger Service Charge (Domestic/Internationa'
            'l)","iata_code":"AL"},{"id":"28145","tax_id":"11","tax_name":"Tax"'
            ',"iata_code":"AM"},{"id":"28146","tax_id":"12","tax_name":"Airport'
            ' Facility Charge (Domestic/International)","iata_code":"AN"},{"id"'
            ':"28147","tax_id":"13","tax_name":"Embarkation Tax (International)'
            '","iata_code":"AO"},{"id":"28148","tax_id":"14","tax_name":"Securi'
            'ty Charge (Domestic/International)","iata_code":"AP"},{"id":"28149'
            '","tax_id":"15","tax_name":"Ticket Tax","iata_code":"AR"},{"id":"2'
            '8150","tax_id":"16","tax_name":"Passenger Security Charge(Domestic'
            '/International)","iata_code":"AT"},{"id":"28151","tax_id":"17","ta'
            'x_name":"Passenger Movement Charge","iata_code":"AU"},{"id":"28152'
            '","tax_id":"18","tax_name":"Tourism Development Tax (International'
            ')","iata_code":"AV"},{"id":"28153","tax_id":"19","tax_name":"Passe'
            'nger Facility and Security Charge","iata_code":"AW"},{"id":"28154"'
            ',"tax_id":"20","tax_name":"Passenger Service Charge (Domestic)","i'
            'ata_code":"AX"},{"id":"28155","tax_id":"21","tax_name":"Passenger '
            'Civil Aviation Security Service Fee (Domestic/International)","iat'
            'a_code":"AY"},{"id":"28156","tax_id":"22","tax_name":"Departure Ta'
            'x (International)","iata_code":"AZ"},{"id":"28157","tax_id":"23","'
            'tax_name":"Passenger Service Charge (Domestic/International)","iat'
            'a_code":"BA"},{"id":"28158","tax_id":"24","tax_name":"Value Added '
            'Tax","iata_code":"BB"},{"id":"28159","tax_id":"25","tax_name":"Air'
            'port Security Charge -(Domestic/International)","iata_code":"BC"},'
            '{"id":"28160","tax_id":"26","tax_name":"Embarkation Fee (Domestic/'
            'International)","iata_code":"BD"},{"id":"28161","tax_id":"27","tax'
            '_name":"Passenger Service and Security Charge","iata_code":"BE"},{'
            '"id":"28162","tax_id":"28","tax_name":"Fiscal Stamp / Security / S'
            'ales / Tourism Tax (Domestic/International)","iata_code":"BF"},{"i'
            'd":"28163","tax_id":"29","tax_name":"Passenger Charge (Domestic/In'
            'ternational)","iata_code":"BG"},{"id":"28164","tax_id":"30","tax_n'
            'ame":"Government Tax","iata_code":"BH"},{"id":"28165","tax_id":"31'
            '","tax_name":"Airport Departure Fee (Domestic/International)","iat'
            'a_code":"BK"},{"id":"28166","tax_id":"32","tax_name":"Aviation Sec'
            'urity Fee","iata_code":"BL"},{"id":"28167","tax_id":"33","tax_name'
            '":"Government Passenger Tax","iata_code":"BM"},{"id":"28168","tax_'
            'id":"34","tax_name":"Passenger Services Charge (International)","i'
            'ata_code":"BN"},{"id":"28169","tax_id":"35","tax_name":"Sales Tax '
            '(Domestic/International)","iata_code":"BO"},{"id":"28170","tax_id"'
            ':"36","tax_name":"PSC, Departure Tax and Contribution to Internati'
            'onal Poverty Eradication ","iata_code":"BP"},{"id":"28171","tax_id'
            '":"37","tax_name":"Airport Fee","iata_code":"BQ"},{"id":"28172","t'
            'ax_id":"38","tax_name":"Embarkation Tax (Domestic/International)",'
            '"iata_code":"BR"},{"id":"28173","tax_id":"39","tax_name":"Ticket T'
            'ax (International)","iata_code":"BS"},{"id":"28174","tax_id":"40",'
            '"tax_name":"Airport Development Fee","iata_code":"BU"},{"id":"2817'
            '5","tax_id":"41","tax_name":"Departure Tax (Domestic/International'
            ')","iata_code":"BW"},{"id":"28176","tax_id":"42","tax_name":"Secur'
            'ity Tax (Domestic/International)","iata_code":"BX"},{"id":"28177",'
            '"tax_id":"43","tax_name":"Sales Tax (International)","iata_code":"'
            'BY"},{"id":"28178","tax_id":"44","tax_name":"Ticket Tax","iata_cod'
            'e":"BZ"},{"id":"28179","tax_id":"45","tax_name":"Air Travellers Se'
            'curity Charge (Domestic/International)","iata_code":"CA"},{"id":"2'
            '8180","tax_id":"46","tax_name":"Passenger Service Charge (Domestic'
            '/International)","iata_code":"CB"},{"id":"28181","tax_id":"47","ta'
            'x_name":"Cocos Island Passenger Service Charge","iata_code":"CC"},'
            '{"id":"28182","tax_id":"48","tax_name":"Embarkation / Sales / Tour'
            'ism Tax (Domestic/International)","iata_code":"CD"},{"id":"28183",'
            '"tax_id":"49","tax_name":"Aviation Security Screening Levy (Domest'
            'ic)","iata_code":"CE"},{"id":"28184","tax_id":"50","tax_name":"Sec'
            'urity Tax","iata_code":"CF"},{"id":"28185","tax_id":"51","tax_name'
            '":"Sales / Security Tax (Domestic/International)","iata_code":"CG"'
            '},{"id":"28186","tax_id":"52","tax_name":"Airport Passenger Securi'
            'ty and Noise Charge (Domestic/International)","iata_code":"CH"},{"'
            'id":"28187","tax_id":"53","tax_name":"Security / Tourism Tax (Dome'
            'stic/International)","iata_code":"CI"},{"id":"28188","tax_id":"54"'
            ',"tax_name":"Security Service Charge (Domestic/International)","ia'
            'ta_code":"CJ"},{"id":"28189","tax_id":"55","tax_name":"Airport Fac'
            'ility Charge (Domestic)","iata_code":"CL"},{"id":"28190","tax_id":'
            '"56","tax_name":"Tax on Value (Domestic/International)","iata_code'
            '":"CM"},{"id":"28191","tax_id":"57","tax_name":"Airport Fee (Domes'
            'tic/International)","iata_code":"CN"},{"id":"28192","tax_id":"58",'
            '"tax_name":"Airport Tax (Domestic/International)","iata_code":"CO"'
            '},{"id":"28193","tax_id":"59","tax_name":"Rehabilitation fund and '
            'care of handicapped person","iata_code":"CQ"},{"id":"28194","tax_i'
            'd":"60","tax_name":"Transportation Tax","iata_code":"CR"},{"id":"2'
            '8195","tax_id":"61","tax_name":"Security Tax (Domestic/Internation'
            'al)","iata_code":"CT"},{"id":"28196","tax_id":"62","tax_name":"Air'
            'port Embarkation Tax (Domestic/International)","iata_code":"CV"},{'
            '"id":"28197","tax_id":"63","tax_name":"Value Added Tax (Domestic)"'
            ',"iata_code":"CW"},{"id":"28198","tax_id":"64","tax_name":"Christm'
            'as Island Passenger Service Charge (Domestic/International)","iata'
            '_code":"CX"},{"id":"28199","tax_id":"65","tax_name":"Airport Servi'
            'ce Charge (International)","iata_code":"CY"},{"id":"28200","tax_id'
            '":"66","tax_name":"Embarkation Tax (Domestic/International)","iata'
            '_code":"CZ"},{"id":"28201","tax_id":"67","tax_name":"Passenger Ser'
            'vice Charge (Domestic)","iata_code":"DA"},{"id":"28202","tax_id":"'
            '68","tax_name":"Airport Security Charge","iata_code":"DB"},{"id":"'
            '28203","tax_id":"69","tax_name":"Security Charge (Domestic/Interna'
            'tional)","iata_code":"DC"},{"id":"28204","tax_id":"70","tax_name":'
            '"Concourse Fee (Intl)","iata_code":"DD"},{"id":"28205","tax_id":"7'
            '1","tax_name":"Airport Security Charge (Domestic/International)","'
            'iata_code":"DE"},{"id":"28206","tax_id":"72","tax_name":"Security '
            'Charge (Intl)","iata_code":"DF"},{"id":"28207","tax_id":"73","tax_'
            'name":"Resident Exit Tax (Timbre)","iata_code":"DG"},{"id":"28208"'
            ',"tax_id":"74","tax_name":"Passenger Facility Charge","iata_code":'
            '"DH"},{"id":"28209","tax_id":"75","tax_name":"Airport Facilitation'
            ' Fee (International)","iata_code":"DI"},{"id":"28210","tax_id":"76'
            '","tax_name":"Departure Tax","iata_code":"DJ"},{"id":"28211","tax_'
            'id":"77","tax_name":"Value Added Tax (Passengers)","iata_code":"DL'
            '"},{"id":"28212","tax_id":"78","tax_name":"Transportation Tax (Int'
            'ernational)","iata_code":"DM"},{"id":"28213","tax_id":"79","tax_na'
            'me":"Value Added Tax (Excess Baggage)","iata_code":"DN"},{"id":"28'
            '214","tax_id":"80","tax_name":"Transportation Tax (Domestic/Intern'
            'ational)","iata_code":"DO"},{"id":"28215","tax_id":"81","tax_name"'
            ':"Goods and Services Tax (GST), (Domestic/International)","iata_co'
            'de":"DP"},{"id":"28216","tax_id":"82","tax_name":"Security Charge '
            '(Domestic/International)","iata_code":"DQ"},{"id":"28217","tax_id"'
            ':"83","tax_name":"Airport Facility Charge (Domestic/International)'
            '","iata_code":"DR"},{"id":"28218","tax_id":"84","tax_name":"Safety'
            ' Fee (Intl)","iata_code":"DS"},{"id":"28219","tax_id":"85","tax_na'
            'me":"Transfer Passenger Fee (Domestic/International)","iata_code":'
            '"DT"},{"id":"28220","tax_id":"86","tax_name":"Embarkation Tax (Dom'
            'estic/International)","iata_code":"DW"},{"id":"28221","tax_id":"87'
            '","tax_name":"Aeronautical Development Charge (Intl)","iata_code":'
            '"DX"},{"id":"28222","tax_id":"88","tax_name":"Tourism Arrival Tax"'
            ',"iata_code":"DY"},{"id":"28223","tax_id":"89","tax_name":"Transpo'
            'rtation / Fiscal / Airport Tax","iata_code":"DZ"},{"id":"28224","t'
            'ax_id":"90","tax_name":"Passenger Departure Tax","iata_code":"EA"}'
            ',{"id":"28225","tax_id":"91","tax_name":"Passenger and Safety Char'
            'ge (Domestic/International)","iata_code":"EB"},{"id":"28226","tax_'
            'id":"92","tax_name":"Government Transportation Tax (Domestic/Inter'
            'national)","iata_code":"EC"},{"id":"28227","tax_id":"93","tax_name'
            '":"Tourism Fee (International)","iata_code":"ED"},{"id":"28228","t'
            'ax_id":"94","tax_name":"Passenger Service Charge (Domestic/Interna'
            'tional)","iata_code":"EE"},{"id":"28229","tax_id":"95","tax_name":'
            '"Security Tax (Domestic/International)","iata_code":"EF"},{"id":"2'
            '8230","tax_id":"96","tax_name":"Transportation Tax","iata_code":"E'
            'G"},{"id":"28231","tax_id":"97","tax_name":"VAT Adjustment Tax (Do'
            'm)","iata_code":"EI"},{"id":"28232","tax_id":"98","tax_name":"PTA '
            'surcharge (International)","iata_code":"EJ"},{"id":"28233","tax_id'
            '":"99","tax_name":"Passenger Service and Security Fee (Domestic/In'
            'ternational)","iata_code":"EK"},{"id":"28234","tax_id":"100","tax_'
            'name":"Airport Improvement Fee","iata_code":"EL"}]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Todo: Add description for test test_taxes_1
    def test_taxes_1(self):

        # Perform the API call through the SDK function
        result = self.controller.taxes()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"pagination":{"offset":0,"limit":100,"count":100,"total":521},"da'
            'ta":[{"id":"28135","tax_id":"1","tax_name":"Government Tax","iata_'
            'code":"AB"},{"id":"28136","tax_id":"2","tax_name":"Value Added Tax'
            '","iata_code":"AC"},{"id":"28137","tax_id":"3","tax_name":"Passeng'
            'er Service Charge (International)","iata_code":"AE"},{"id":"28138"'
            ',"tax_id":"4","tax_name":"Airport Departure Fee (Domestic/Internat'
            'ional)","iata_code":"AF"},{"id":"28139","tax_id":"5","tax_name":"T'
            'icket Tax","iata_code":"AG"},{"id":"28140","tax_id":"6","tax_name"'
            ':"Airport Tax","iata_code":"AH"},{"id":"28141","tax_id":"7","tax_n'
            'ame":"Baggage Security Screening Fee","iata_code":"AI"},{"id":"281'
            '42","tax_id":"8","tax_name":"Airport Exit Tax (International)","ia'
            'ta_code":"AJ"},{"id":"28143","tax_id":"9","tax_name":"Airport Depa'
            'rture Tax (International)","iata_code":"AK"},{"id":"28144","tax_id'
            '":"10","tax_name":"Passenger Service Charge (Domestic/Internationa'
            'l)","iata_code":"AL"},{"id":"28145","tax_id":"11","tax_name":"Tax"'
            ',"iata_code":"AM"},{"id":"28146","tax_id":"12","tax_name":"Airport'
            ' Facility Charge (Domestic/International)","iata_code":"AN"},{"id"'
            ':"28147","tax_id":"13","tax_name":"Embarkation Tax (International)'
            '","iata_code":"AO"},{"id":"28148","tax_id":"14","tax_name":"Securi'
            'ty Charge (Domestic/International)","iata_code":"AP"},{"id":"28149'
            '","tax_id":"15","tax_name":"Ticket Tax","iata_code":"AR"},{"id":"2'
            '8150","tax_id":"16","tax_name":"Passenger Security Charge(Domestic'
            '/International)","iata_code":"AT"},{"id":"28151","tax_id":"17","ta'
            'x_name":"Passenger Movement Charge","iata_code":"AU"},{"id":"28152'
            '","tax_id":"18","tax_name":"Tourism Development Tax (International'
            ')","iata_code":"AV"},{"id":"28153","tax_id":"19","tax_name":"Passe'
            'nger Facility and Security Charge","iata_code":"AW"},{"id":"28154"'
            ',"tax_id":"20","tax_name":"Passenger Service Charge (Domestic)","i'
            'ata_code":"AX"},{"id":"28155","tax_id":"21","tax_name":"Passenger '
            'Civil Aviation Security Service Fee (Domestic/International)","iat'
            'a_code":"AY"},{"id":"28156","tax_id":"22","tax_name":"Departure Ta'
            'x (International)","iata_code":"AZ"},{"id":"28157","tax_id":"23","'
            'tax_name":"Passenger Service Charge (Domestic/International)","iat'
            'a_code":"BA"},{"id":"28158","tax_id":"24","tax_name":"Value Added '
            'Tax","iata_code":"BB"},{"id":"28159","tax_id":"25","tax_name":"Air'
            'port Security Charge -(Domestic/International)","iata_code":"BC"},'
            '{"id":"28160","tax_id":"26","tax_name":"Embarkation Fee (Domestic/'
            'International)","iata_code":"BD"},{"id":"28161","tax_id":"27","tax'
            '_name":"Passenger Service and Security Charge","iata_code":"BE"},{'
            '"id":"28162","tax_id":"28","tax_name":"Fiscal Stamp / Security / S'
            'ales / Tourism Tax (Domestic/International)","iata_code":"BF"},{"i'
            'd":"28163","tax_id":"29","tax_name":"Passenger Charge (Domestic/In'
            'ternational)","iata_code":"BG"},{"id":"28164","tax_id":"30","tax_n'
            'ame":"Government Tax","iata_code":"BH"},{"id":"28165","tax_id":"31'
            '","tax_name":"Airport Departure Fee (Domestic/International)","iat'
            'a_code":"BK"},{"id":"28166","tax_id":"32","tax_name":"Aviation Sec'
            'urity Fee","iata_code":"BL"},{"id":"28167","tax_id":"33","tax_name'
            '":"Government Passenger Tax","iata_code":"BM"},{"id":"28168","tax_'
            'id":"34","tax_name":"Passenger Services Charge (International)","i'
            'ata_code":"BN"},{"id":"28169","tax_id":"35","tax_name":"Sales Tax '
            '(Domestic/International)","iata_code":"BO"},{"id":"28170","tax_id"'
            ':"36","tax_name":"PSC, Departure Tax and Contribution to Internati'
            'onal Poverty Eradication ","iata_code":"BP"},{"id":"28171","tax_id'
            '":"37","tax_name":"Airport Fee","iata_code":"BQ"},{"id":"28172","t'
            'ax_id":"38","tax_name":"Embarkation Tax (Domestic/International)",'
            '"iata_code":"BR"},{"id":"28173","tax_id":"39","tax_name":"Ticket T'
            'ax (International)","iata_code":"BS"},{"id":"28174","tax_id":"40",'
            '"tax_name":"Airport Development Fee","iata_code":"BU"},{"id":"2817'
            '5","tax_id":"41","tax_name":"Departure Tax (Domestic/International'
            ')","iata_code":"BW"},{"id":"28176","tax_id":"42","tax_name":"Secur'
            'ity Tax (Domestic/International)","iata_code":"BX"},{"id":"28177",'
            '"tax_id":"43","tax_name":"Sales Tax (International)","iata_code":"'
            'BY"},{"id":"28178","tax_id":"44","tax_name":"Ticket Tax","iata_cod'
            'e":"BZ"},{"id":"28179","tax_id":"45","tax_name":"Air Travellers Se'
            'curity Charge (Domestic/International)","iata_code":"CA"},{"id":"2'
            '8180","tax_id":"46","tax_name":"Passenger Service Charge (Domestic'
            '/International)","iata_code":"CB"},{"id":"28181","tax_id":"47","ta'
            'x_name":"Cocos Island Passenger Service Charge","iata_code":"CC"},'
            '{"id":"28182","tax_id":"48","tax_name":"Embarkation / Sales / Tour'
            'ism Tax (Domestic/International)","iata_code":"CD"},{"id":"28183",'
            '"tax_id":"49","tax_name":"Aviation Security Screening Levy (Domest'
            'ic)","iata_code":"CE"},{"id":"28184","tax_id":"50","tax_name":"Sec'
            'urity Tax","iata_code":"CF"},{"id":"28185","tax_id":"51","tax_name'
            '":"Sales / Security Tax (Domestic/International)","iata_code":"CG"'
            '},{"id":"28186","tax_id":"52","tax_name":"Airport Passenger Securi'
            'ty and Noise Charge (Domestic/International)","iata_code":"CH"},{"'
            'id":"28187","tax_id":"53","tax_name":"Security / Tourism Tax (Dome'
            'stic/International)","iata_code":"CI"},{"id":"28188","tax_id":"54"'
            ',"tax_name":"Security Service Charge (Domestic/International)","ia'
            'ta_code":"CJ"},{"id":"28189","tax_id":"55","tax_name":"Airport Fac'
            'ility Charge (Domestic)","iata_code":"CL"},{"id":"28190","tax_id":'
            '"56","tax_name":"Tax on Value (Domestic/International)","iata_code'
            '":"CM"},{"id":"28191","tax_id":"57","tax_name":"Airport Fee (Domes'
            'tic/International)","iata_code":"CN"},{"id":"28192","tax_id":"58",'
            '"tax_name":"Airport Tax (Domestic/International)","iata_code":"CO"'
            '},{"id":"28193","tax_id":"59","tax_name":"Rehabilitation fund and '
            'care of handicapped person","iata_code":"CQ"},{"id":"28194","tax_i'
            'd":"60","tax_name":"Transportation Tax","iata_code":"CR"},{"id":"2'
            '8195","tax_id":"61","tax_name":"Security Tax (Domestic/Internation'
            'al)","iata_code":"CT"},{"id":"28196","tax_id":"62","tax_name":"Air'
            'port Embarkation Tax (Domestic/International)","iata_code":"CV"},{'
            '"id":"28197","tax_id":"63","tax_name":"Value Added Tax (Domestic)"'
            ',"iata_code":"CW"},{"id":"28198","tax_id":"64","tax_name":"Christm'
            'as Island Passenger Service Charge (Domestic/International)","iata'
            '_code":"CX"},{"id":"28199","tax_id":"65","tax_name":"Airport Servi'
            'ce Charge (International)","iata_code":"CY"},{"id":"28200","tax_id'
            '":"66","tax_name":"Embarkation Tax (Domestic/International)","iata'
            '_code":"CZ"},{"id":"28201","tax_id":"67","tax_name":"Passenger Ser'
            'vice Charge (Domestic)","iata_code":"DA"},{"id":"28202","tax_id":"'
            '68","tax_name":"Airport Security Charge","iata_code":"DB"},{"id":"'
            '28203","tax_id":"69","tax_name":"Security Charge (Domestic/Interna'
            'tional)","iata_code":"DC"},{"id":"28204","tax_id":"70","tax_name":'
            '"Concourse Fee (Intl)","iata_code":"DD"},{"id":"28205","tax_id":"7'
            '1","tax_name":"Airport Security Charge (Domestic/International)","'
            'iata_code":"DE"},{"id":"28206","tax_id":"72","tax_name":"Security '
            'Charge (Intl)","iata_code":"DF"},{"id":"28207","tax_id":"73","tax_'
            'name":"Resident Exit Tax (Timbre)","iata_code":"DG"},{"id":"28208"'
            ',"tax_id":"74","tax_name":"Passenger Facility Charge","iata_code":'
            '"DH"},{"id":"28209","tax_id":"75","tax_name":"Airport Facilitation'
            ' Fee (International)","iata_code":"DI"},{"id":"28210","tax_id":"76'
            '","tax_name":"Departure Tax","iata_code":"DJ"},{"id":"28211","tax_'
            'id":"77","tax_name":"Value Added Tax (Passengers)","iata_code":"DL'
            '"},{"id":"28212","tax_id":"78","tax_name":"Transportation Tax (Int'
            'ernational)","iata_code":"DM"},{"id":"28213","tax_id":"79","tax_na'
            'me":"Value Added Tax (Excess Baggage)","iata_code":"DN"},{"id":"28'
            '214","tax_id":"80","tax_name":"Transportation Tax (Domestic/Intern'
            'ational)","iata_code":"DO"},{"id":"28215","tax_id":"81","tax_name"'
            ':"Goods and Services Tax (GST), (Domestic/International)","iata_co'
            'de":"DP"},{"id":"28216","tax_id":"82","tax_name":"Security Charge '
            '(Domestic/International)","iata_code":"DQ"},{"id":"28217","tax_id"'
            ':"83","tax_name":"Airport Facility Charge (Domestic/International)'
            '","iata_code":"DR"},{"id":"28218","tax_id":"84","tax_name":"Safety'
            ' Fee (Intl)","iata_code":"DS"},{"id":"28219","tax_id":"85","tax_na'
            'me":"Transfer Passenger Fee (Domestic/International)","iata_code":'
            '"DT"},{"id":"28220","tax_id":"86","tax_name":"Embarkation Tax (Dom'
            'estic/International)","iata_code":"DW"},{"id":"28221","tax_id":"87'
            '","tax_name":"Aeronautical Development Charge (Intl)","iata_code":'
            '"DX"},{"id":"28222","tax_id":"88","tax_name":"Tourism Arrival Tax"'
            ',"iata_code":"DY"},{"id":"28223","tax_id":"89","tax_name":"Transpo'
            'rtation / Fiscal / Airport Tax","iata_code":"DZ"},{"id":"28224","t'
            'ax_id":"90","tax_name":"Passenger Departure Tax","iata_code":"EA"}'
            ',{"id":"28225","tax_id":"91","tax_name":"Passenger and Safety Char'
            'ge (Domestic/International)","iata_code":"EB"},{"id":"28226","tax_'
            'id":"92","tax_name":"Government Transportation Tax (Domestic/Inter'
            'national)","iata_code":"EC"},{"id":"28227","tax_id":"93","tax_name'
            '":"Tourism Fee (International)","iata_code":"ED"},{"id":"28228","t'
            'ax_id":"94","tax_name":"Passenger Service Charge (Domestic/Interna'
            'tional)","iata_code":"EE"},{"id":"28229","tax_id":"95","tax_name":'
            '"Security Tax (Domestic/International)","iata_code":"EF"},{"id":"2'
            '8230","tax_id":"96","tax_name":"Transportation Tax","iata_code":"E'
            'G"},{"id":"28231","tax_id":"97","tax_name":"VAT Adjustment Tax (Do'
            'm)","iata_code":"EI"},{"id":"28232","tax_id":"98","tax_name":"PTA '
            'surcharge (International)","iata_code":"EJ"},{"id":"28233","tax_id'
            '":"99","tax_name":"Passenger Service and Security Fee (Domestic/In'
            'ternational)","iata_code":"EK"},{"id":"28234","tax_id":"100","tax_'
            'name":"Airport Improvement Fee","iata_code":"EL"}]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

